# Generated by Django 3.1.3 on 2020-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_hrprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile/default2.jpg', upload_to='images/profile'),
        ),
    ]
